# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/idiot66',
                'doc_host': 'https://andbo.github.io',
                'git_url': 'https://github.com/andbo/idiot66',
                'lib_path': 'idiot66'},
  'syms': {'idiot66.core': {'idiot66.core.foo': ('core.html#foo', 'idiot66/core.py')}}}
